alias "$"=''
alias ls='lsd'
alias l='lsd -l'
alias ll='lsd -l'
alias la='lsd -a'
alias lla='lsd -la'
alias lt='lsd --tree'
alias c='clear'
alias h='history'

alias vi='nvim'
alias d='docker'
alias dc='docker compose'
alias tf='terraform'
alias ca='cargo'
alias p='pnpm'
alias cur='cursor'

alias gp='git pull'
alias gll='git log --oneline'
alias glf='git log --pretty=fuller'
alias gprune='git branch -vv | grep ": gone]" | awk '\''{print $1}'\'' | xargs -I{} git branch -D {}'
alias grh='git reset --hard'
alias gb='git branch'
alias gba='git branch -a'
alias gs='git switch'
alias gsc='git switch -c'

alias teee='tee >(pbcopy)'
alias ze='nvim ~/.zshrc && source ~/.zshrc'
alias ff='find . -type f'
alias fd='find . -type d'
alias df='df -h'
alias du='du -ch'

alias br='brew'
alias brl='brew leaves -r'